name: Build Python Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5 sounddevice soundfile
       
        if [ "$RUNNER_OS" == "Windows" ]; then
          pip install pywin32
        fi
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libportaudio2 libsndfile1
        fi
    
    - name: Run PyInstaller
      run: |
        pyinstaller --onefile --windowed --name MyApp main.py
        
        if [ "$RUNNER_OS" == "Windows" ]; then
          pyinstaller --onefile --windowed --name MyApp --add-binary "path/to/any/extra/dlls;." main.py
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-build
        path: dist/