name: Build Python Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5 sounddevice soundfile
    
    - name: Install Windows-specific dependencies
      if: runner.os == 'Windows'
      run: |
        pip install pywin32
    
    - name: Install Linux system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libportaudio2 libsndfile1 python3-pyqt5
    
    - name: Run PyInstaller (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --icon=assert/logo.ico --name MusicPlayer main.py
    
    - name: Run PyInstaller (Linux)
      if: runner.os == 'Linux'
      run: |
        pyinstaller --onefile --windowed --icon=assert/logo.ico --name MusicPlayer main.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-build
        path: dist/